[2025-03-04T14:59:05.006+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T14:59:05.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T14:59:05.035+0000] {logging_mixin.py:190} INFO - [2025-03-04T14:59:05.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T14:59:05.142+0000] {logging_mixin.py:190} INFO - [2025-03-04T14:59:05.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T14:59:05.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T14:59:05.295+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.335 seconds
[2025-03-04T14:59:35.815+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T14:59:35.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T14:59:35.861+0000] {logging_mixin.py:190} INFO - [2025-03-04T14:59:35.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T14:59:35.964+0000] {logging_mixin.py:190} INFO - [2025-03-04T14:59:35.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T14:59:35.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T14:59:36.056+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.307 seconds
[2025-03-04T15:00:06.598+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:00:06.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:00:06.613+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:00:06.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:00:06.710+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:00:06.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:00:06.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:00:06.848+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.281 seconds
[2025-03-04T15:00:37.143+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:00:37.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:00:37.153+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:00:37.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:00:37.199+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:00:37.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:00:37.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:00:37.252+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.125 seconds
[2025-03-04T15:06:47.025+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:06:47.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:06:47.044+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:06:47.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:06:47.092+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:06:47.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:06:47.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:06:47.165+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.178 seconds
[2025-03-04T15:07:17.329+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:07:17.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:07:17.340+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:07:17.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:07:17.383+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:07:17.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:07:17.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:07:17.453+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.137 seconds
[2025-03-04T15:07:47.966+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:07:47.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:07:47.973+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:07:47.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:07:48.001+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:07:47.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:07:48.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:07:48.035+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.082 seconds
[2025-03-04T15:08:18.438+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:08:18.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:08:18.451+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:08:18.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:08:18.477+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:08:18.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:08:18.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:08:18.523+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.097 seconds
[2025-03-04T15:08:48.920+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:08:48.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:08:48.927+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:08:48.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:08:48.959+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:08:48.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:08:48.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:08:49.003+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.094 seconds
[2025-03-04T15:09:19.512+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:09:19.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:09:19.517+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:09:19.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:09:19.545+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:09:19.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:09:19.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:09:19.573+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.069 seconds
[2025-03-04T15:09:49.964+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:09:49.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:09:49.968+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:09:49.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:09:49.997+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:09:49.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:09:50.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:09:50.030+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.075 seconds
[2025-03-04T15:10:20.560+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:10:20.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:10:20.570+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:10:20.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:10:20.594+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:10:20.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:10:20.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:10:20.630+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.079 seconds
[2025-03-04T15:10:51.115+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:10:51.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:10:51.120+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:10:51.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:10:51.152+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:10:51.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:10:51.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:10:51.185+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.081 seconds
[2025-03-04T15:11:21.637+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:11:21.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:11:21.643+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:11:21.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:11:21.669+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:11:21.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:11:21.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:11:21.710+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.083 seconds
[2025-03-04T15:11:52.249+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:11:52.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:11:52.256+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:11:52.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:11:52.284+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:11:52.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:11:52.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:11:52.321+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.081 seconds
[2025-03-04T15:12:22.841+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:12:22.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:12:22.847+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:12:22.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:12:22.876+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:12:22.869+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:12:22.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:12:22.950+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.148 seconds
[2025-03-04T15:12:53.112+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:12:53.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:12:53.118+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:12:53.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:12:53.152+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:12:53.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:12:53.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:12:53.188+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.082 seconds
[2025-03-04T15:13:23.305+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:13:23.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:13:23.312+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:13:23.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:13:23.353+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:13:23.346+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:13:23.356+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:13:23.452+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.167 seconds
[2025-03-04T15:13:53.962+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:13:53.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:13:53.969+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:13:53.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:13:53.997+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:13:53.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:13:53.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:13:54.022+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.077 seconds
[2025-03-04T15:14:24.193+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:14:24.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:14:24.199+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:14:24.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:14:24.226+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:14:24.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:14:24.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:14:24.271+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.084 seconds
[2025-03-04T15:16:35.241+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:16:35.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:16:35.270+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:16:35.268+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:16:35.375+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:16:35.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:16:35.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:16:35.589+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.433 seconds
[2025-03-04T15:17:06.117+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:17:06.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:17:06.134+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:17:06.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:17:06.164+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:17:06.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:17:06.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:17:06.202+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.094 seconds
[2025-03-04T15:17:36.424+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:17:36.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:17:36.430+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:17:36.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:17:36.458+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:17:36.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:17:36.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:17:36.492+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.075 seconds
[2025-03-04T15:18:06.862+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:18:06.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:18:06.870+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:18:06.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:18:06.910+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:18:06.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:18:06.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:18:06.958+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.108 seconds
[2025-03-04T15:18:37.390+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:18:37.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:18:37.396+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:18:37.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:18:37.429+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:18:37.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:18:37.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:18:37.462+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.082 seconds
[2025-03-04T15:19:07.899+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:19:07.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:19:07.904+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:19:07.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:19:07.928+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:19:07.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:19:07.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:19:07.965+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.077 seconds
[2025-03-04T15:19:38.393+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:19:38.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:19:38.398+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:19:38.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:19:38.429+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:19:38.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:19:38.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:19:38.462+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.078 seconds
[2025-03-04T15:20:08.753+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:20:08.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:20:08.762+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:20:08.762+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:20:08.787+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:20:08.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:20:08.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:20:08.827+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.083 seconds
[2025-03-04T15:20:39.322+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:20:39.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:20:39.328+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:20:39.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:20:39.356+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:20:39.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:20:39.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:20:39.397+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.095 seconds
[2025-03-04T15:21:09.767+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:21:09.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:21:09.782+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:21:09.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:21:09.807+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:21:09.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:21:09.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:21:09.868+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.108 seconds
[2025-03-04T15:21:40.522+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:21:40.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:21:40.530+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:21:40.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:21:40.570+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:21:40.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:21:40.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:21:40.642+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.143 seconds
[2025-03-04T15:22:11.142+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:22:11.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:22:11.158+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:22:11.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:22:11.212+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:22:11.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:22:11.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:22:11.279+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.157 seconds
[2025-03-04T15:22:41.747+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:22:41.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:22:41.753+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:22:41.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:22:41.785+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:22:41.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:22:41.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:22:41.856+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.125 seconds
[2025-03-04T15:23:12.355+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:23:12.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:23:12.379+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:23:12.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:23:12.408+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:23:12.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:23:12.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:23:12.816+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.479 seconds
[2025-03-04T15:23:43.285+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:23:43.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:23:43.292+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:23:43.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:23:43.321+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:23:43.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:23:43.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:23:43.361+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.084 seconds
[2025-03-04T15:24:13.839+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:24:13.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:24:13.848+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:24:13.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:24:13.880+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:24:13.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:24:13.884+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:24:13.933+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.118 seconds
[2025-03-04T15:24:44.089+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:24:44.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:24:44.095+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:24:44.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:24:44.124+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:24:44.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:24:44.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:24:44.160+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.080 seconds
[2025-03-04T15:25:14.347+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:25:14.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:25:14.354+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:25:14.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:25:14.380+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:25:14.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:25:14.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:25:14.412+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.073 seconds
[2025-03-04T15:25:44.557+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:25:44.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:25:44.564+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:25:44.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:25:44.594+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:25:44.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:25:44.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:25:44.631+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.087 seconds
[2025-03-04T15:26:14.731+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:26:14.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:26:14.739+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:26:14.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:26:14.764+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:26:14.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:26:14.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:26:14.796+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.073 seconds
[2025-03-04T15:26:45.240+0000] {processor.py:186} INFO - Started process (PID=485) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:26:45.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:26:45.246+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:26:45.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:26:45.276+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:26:45.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:26:45.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:26:45.320+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.090 seconds
[2025-03-04T15:27:15.569+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:27:15.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:27:15.574+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:27:15.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:27:15.604+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:27:15.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:27:15.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:27:15.646+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.085 seconds
[2025-03-04T15:27:45.904+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:27:45.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:27:45.909+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:27:45.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:27:45.936+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:27:45.929+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:27:45.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:27:45.973+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.078 seconds
[2025-03-04T15:28:16.189+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:28:16.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:28:16.194+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:28:16.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:28:16.233+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:28:16.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:28:16.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:28:16.267+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.087 seconds
[2025-03-04T15:28:46.679+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:28:46.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:28:46.686+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:28:46.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:28:46.716+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:28:46.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:28:46.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:28:46.750+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.080 seconds
[2025-03-04T15:29:16.952+0000] {processor.py:186} INFO - Started process (PID=565) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:29:16.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:29:16.961+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:29:16.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:29:16.985+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:29:16.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:29:16.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:29:17.019+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.075 seconds
[2025-03-04T15:29:47.211+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:29:47.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:29:47.270+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:29:47.269+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:29:47.323+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:29:47.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:29:47.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:29:47.365+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.163 seconds
[2025-03-04T15:30:17.598+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:30:17.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:30:17.606+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:30:17.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:30:17.629+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:30:17.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:30:17.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:30:17.661+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.076 seconds
[2025-03-04T15:30:47.807+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:30:47.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:30:47.814+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:30:47.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:30:47.846+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:30:47.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:30:47.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:30:47.882+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.087 seconds
[2025-03-04T15:31:18.046+0000] {processor.py:186} INFO - Started process (PID=623) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:31:18.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:31:18.157+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:31:18.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:31:18.212+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:31:18.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:31:18.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:31:18.326+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.290 seconds
[2025-03-04T15:31:48.731+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:31:48.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:31:48.737+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:31:48.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:31:48.763+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:31:48.757+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:31:48.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:31:48.798+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.077 seconds
[2025-03-04T15:32:18.917+0000] {processor.py:186} INFO - Started process (PID=655) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:32:18.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:32:18.923+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:32:18.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:32:18.947+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:32:18.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:32:18.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:32:18.983+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.078 seconds
[2025-03-04T15:32:49.128+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:32:49.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:32:49.136+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:32:49.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:32:49.172+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:32:49.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:32:49.175+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:32:49.204+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.086 seconds
[2025-03-04T15:33:19.604+0000] {processor.py:186} INFO - Started process (PID=687) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:33:19.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:33:19.611+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:33:19.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:33:19.639+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:33:19.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:33:19.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:33:19.676+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.081 seconds
[2025-03-04T15:33:49.963+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:33:49.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:33:49.971+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:33:49.970+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:33:49.998+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:33:49.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:33:50.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:33:50.033+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.080 seconds
[2025-03-04T15:34:20.595+0000] {processor.py:186} INFO - Started process (PID=719) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:34:20.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:34:20.635+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:34:20.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:34:20.687+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:34:20.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:34:20.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:34:21.634+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 1.100 seconds
[2025-03-04T15:34:51.878+0000] {processor.py:186} INFO - Started process (PID=740) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:34:51.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:34:51.884+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:34:51.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:34:51.906+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:34:51.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:34:51.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:34:51.943+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.075 seconds
[2025-03-04T15:35:22.387+0000] {processor.py:186} INFO - Started process (PID=751) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:35:22.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:35:22.397+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:35:22.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:35:22.429+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:35:22.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:35:22.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:35:22.471+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.098 seconds
[2025-03-04T15:35:52.659+0000] {processor.py:186} INFO - Started process (PID=767) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:35:52.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:35:52.665+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:35:52.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:35:52.693+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:35:52.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:35:52.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:35:52.728+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.078 seconds
[2025-03-04T15:36:23.173+0000] {processor.py:186} INFO - Started process (PID=783) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:36:23.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:36:23.179+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:36:23.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:36:23.208+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:36:23.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:36:23.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:36:23.242+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.081 seconds
[2025-03-04T15:36:53.815+0000] {processor.py:186} INFO - Started process (PID=799) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:36:53.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:36:53.823+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:36:53.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:36:53.849+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:36:53.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:36:53.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:36:53.895+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.089 seconds
[2025-03-04T15:37:24.174+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:37:24.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:37:24.179+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:37:24.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:37:24.213+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:37:24.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:37:24.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:37:24.251+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.086 seconds
[2025-03-04T15:37:54.524+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:37:54.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:37:54.539+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:37:54.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:37:54.670+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:37:54.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:37:54.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:37:54.747+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.238 seconds
[2025-03-04T15:38:25.023+0000] {processor.py:186} INFO - Started process (PID=847) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:38:25.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:38:25.030+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:38:25.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:38:25.059+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:38:25.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:38:25.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:38:25.095+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.082 seconds
[2025-03-04T15:38:55.309+0000] {processor.py:186} INFO - Started process (PID=863) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:38:55.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:38:55.316+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:38:55.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:38:55.349+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:38:55.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:38:55.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:38:55.384+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.086 seconds
[2025-03-04T15:40:51.898+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:40:51.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:40:51.910+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:40:51.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:40:51.958+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:40:51.944+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:40:51.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:40:52.054+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.180 seconds
[2025-03-04T15:41:22.843+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:41:22.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:41:22.858+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:41:22.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:41:22.888+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:41:22.882+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:41:22.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:41:22.949+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.122 seconds
[2025-03-04T15:41:53.040+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:41:53.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:41:53.045+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:41:53.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:41:53.075+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:41:53.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:41:53.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:41:53.108+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.078 seconds
[2025-03-04T15:42:23.756+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:42:23.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:42:23.765+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:42:23.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:42:23.793+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:42:23.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:42:23.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:42:23.827+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.086 seconds
[2025-03-04T15:42:54.287+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:42:54.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:42:54.293+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:42:54.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:42:54.325+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:42:54.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:42:54.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:42:54.358+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.080 seconds
[2025-03-04T15:43:24.646+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:43:24.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:43:24.675+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:43:24.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:43:24.761+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:43:24.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:43:24.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:43:24.840+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.218 seconds
[2025-03-04T15:43:55.141+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:43:55.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:43:55.148+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:43:55.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:43:55.185+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:43:55.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:43:55.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:43:55.236+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.111 seconds
[2025-03-04T15:44:25.677+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:44:25.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:44:25.690+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:44:25.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:44:25.724+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:44:25.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/airflow_module/dags/data_modules/data_extraction.py", line 1, in <module>
    from airflow_module.dags.data_modules.db_connection import postgre_connection
ModuleNotFoundError: No module named 'airflow_module'
[2025-03-04T15:44:25.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:44:25.753+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.085 seconds
[2025-03-04T15:44:54.202+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:44:54.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:44:54.210+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:44:54.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:44:54.225+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:44:54.225+0000] {dagbag.py:366} INFO - File /opt/airflow/airflow_module/dags/data_modules/data_extraction.py assumed to contain no DAGs. Skipping.
[2025-03-04T15:44:54.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:44:54.259+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.064 seconds
[2025-03-04T15:45:24.891+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:45:24.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/airflow_module/dags/data_modules/data_extraction.py for tasks to queue
[2025-03-04T15:45:24.896+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:45:24.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:45:24.915+0000] {logging_mixin.py:190} INFO - [2025-03-04T15:45:24.915+0000] {dagbag.py:366} INFO - File /opt/airflow/airflow_module/dags/data_modules/data_extraction.py assumed to contain no DAGs. Skipping.
[2025-03-04T15:45:24.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/airflow_module/dags/data_modules/data_extraction.py
[2025-03-04T15:45:24.943+0000] {processor.py:208} INFO - Processing /opt/airflow/airflow_module/dags/data_modules/data_extraction.py took 0.062 seconds
